### ISSUE TITLE
Package on pypi is missing VERSION file

### ISSUE THREAD

**Issue by rio** [opentracing-contrib/python-sqlalchemy#1]
The package served from [pypi](https://pypi.python.org/pypi/sqlalchemy-opentracing/0.1.4) is missing the VERSION file. This makes the package install fail via pip:

```
Collecting sqlalchemy_opentracing
  Downloading sqlalchemy_opentracing-0.1.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-loTWHp/sqlalchemy-opentracing/setup.py", line 3, in <module>
        version = open('VERSION').read()
    IOError: [Errno 2] No such file or directory: 'VERSION'
```

**Comment by Mahito** [comment]
I got the same error.
I found that `VERSION` file is not included in the package.

```
% tar xvfz sqlalchemy_opentracing-0.1.4.tar.gz
x sqlalchemy_opentracing-0.1.4/
x sqlalchemy_opentracing-0.1.4/PKG-INFO
x sqlalchemy_opentracing-0.1.4/README.rst
x sqlalchemy_opentracing-0.1.4/setup.cfg
x sqlalchemy_opentracing-0.1.4/setup.py
x sqlalchemy_opentracing-0.1.4/sqlalchemy_opentracing/
x sqlalchemy_opentracing-0.1.4/sqlalchemy_opentracing/__init__.py
x sqlalchemy_opentracing-0.1.4/sqlalchemy_opentracing.egg-info/
x sqlalchemy_opentracing-0.1.4/sqlalchemy_opentracing.egg-info/dependency_links.txt
x sqlalchemy_opentracing-0.1.4/sqlalchemy_opentracing.egg-info/PKG-INFO
x sqlalchemy_opentracing-0.1.4/sqlalchemy_opentracing.egg-info/requires.txt
x sqlalchemy_opentracing-0.1.4/sqlalchemy_opentracing.egg-info/SOURCES.txt
x sqlalchemy_opentracing-0.1.4/sqlalchemy_opentracing.egg-info/top_level.txt
```

The cause that the VERSION file is not included may be as follows

https://docs.python.org/2/distutils/sourcedist.html
> Changed in version 2.7.3: sdist will read a MANIFEST file if no MANIFEST.in exists, like it did before 2.7.

https://docs.python.org/3.6/distutils/sourcedist.html#creating-a-source-distribution
> Changed in version 3.2.2: sdist will read a MANIFEST file if no MANIFEST.in exists, like it used to do.

**Comment by Mahito** [comment]
I can't still install from pypi.
I think that files should be re-uploaded to pypi using a command like `python setup.py sdist upload`

**Comment by carlosalberto** [comment]
I just deployed again to PyPi. Should be working now ;)
