### ISSUE TITLE
No LICENSE file

### ISSUE THREAD

**Issue by TimDumol** [opentracing-contrib/python-sqlalchemy#3]
The setup.py file states that the code is under the BSD license, but there is no corresponding LICENSE file. Having a corresponding LICENSE file would make it a lot clearer.

**Comment by carlosalberto** [comment]
Fixed in be9783da906437c31fe9265e7f82d33e51f056ce - but now we use the Apache 2.0 License (as this is the license other OT projects use or will be using).
